set_property PACKAGE_PIN Y18 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property PACKAGE_PIN P20 [get_ports rst_in]
set_property IOSTANDARD LVCMOS33 [get_ports rst_in]
set_property PACKAGE_PIN Y19 [get_ports rx]
set_property IOSTANDARD LVCMOS33 [get_ports rx]
set_property PACKAGE_PIN V18 [get_ports tx]
set_property IOSTANDARD LVCMOS33 [get_ports tx]
set_property PACKAGE_PIN A21 [get_ports start_pg_led]
set_property IOSTANDARD LVCMOS33 [get_ports start_pg_led]
set_property DRIVE 12 [get_ports start_pg_led]
set_property SLEW SLOW [get_ports start_pg_led]
set_property PACKAGE_PIN W4 [get_ports start_pg]
set_property IOSTANDARD LVCMOS33 [get_ports start_pg]

# GPIOA Red and Yellow LED
set_property PACKAGE_PIN K17 [get_ports {gpio_a_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_a_out[0]}]
set_property DRIVE 12 [get_ports {gpio_a_out[0]}]
set_property SLEW SLOW [get_ports {gpio_a_out[0]}]
set_property PACKAGE_PIN L13 [get_ports {gpio_a_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_a_out[1]}]
set_property DRIVE 12 [get_ports {gpio_a_out[1]}]
set_property SLEW SLOW [get_ports {gpio_a_out[1]}]
set_property PACKAGE_PIN M13 [get_ports {gpio_a_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_a_out[2]}]
set_property DRIVE 12 [get_ports {gpio_a_out[2]}]
set_property SLEW SLOW [get_ports {gpio_a_out[2]}]
set_property PACKAGE_PIN K14 [get_ports {gpio_a_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_a_out[3]}]
set_property DRIVE 12 [get_ports {gpio_a_out[3]}]
set_property SLEW SLOW [get_ports {gpio_a_out[3]}]
set_property PACKAGE_PIN K13 [get_ports {gpio_a_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_a_out[4]}]
set_property DRIVE 12 [get_ports {gpio_a_out[4]}]
set_property SLEW SLOW [get_ports {gpio_a_out[4]}]
set_property PACKAGE_PIN M20 [get_ports {gpio_a_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_a_out[5]}]
set_property DRIVE 12 [get_ports {gpio_a_out[5]}]
set_property SLEW SLOW [get_ports {gpio_a_out[5]}]
set_property PACKAGE_PIN N20 [get_ports {gpio_a_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_a_out[6]}]
set_property DRIVE 12 [get_ports {gpio_a_out[6]}]
set_property SLEW SLOW [get_ports {gpio_a_out[6]}]
set_property PACKAGE_PIN N19 [get_ports {gpio_a_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_a_out[7]}]
set_property DRIVE 12 [get_ports {gpio_a_out[7]}]
set_property SLEW SLOW [get_ports {gpio_a_out[7]}]
set_property PACKAGE_PIN M17 [get_ports {gpio_a_out[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_a_out[8]}]
set_property DRIVE 12 [get_ports {gpio_a_out[8]}]
set_property SLEW SLOW [get_ports {gpio_a_out[8]}]
set_property PACKAGE_PIN M16 [get_ports {gpio_a_out[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_a_out[9]}]
set_property DRIVE 12 [get_ports {gpio_a_out[9]}]
set_property SLEW SLOW [get_ports {gpio_a_out[9]}]
set_property PACKAGE_PIN M15 [get_ports {gpio_a_out[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_a_out[10]}]
set_property DRIVE 12 [get_ports {gpio_a_out[10]}]
set_property SLEW SLOW [get_ports {gpio_a_out[10]}]
set_property PACKAGE_PIN K16 [get_ports {gpio_a_out[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_a_out[11]}]
set_property DRIVE 12 [get_ports {gpio_a_out[11]}]
set_property SLEW SLOW [get_ports {gpio_a_out[11]}]
set_property PACKAGE_PIN L16 [get_ports {gpio_a_out[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_a_out[12]}]
set_property DRIVE 12 [get_ports {gpio_a_out[12]}]
set_property SLEW SLOW [get_ports {gpio_a_out[12]}]
set_property PACKAGE_PIN L15 [get_ports {gpio_a_out[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_a_out[13]}]
set_property DRIVE 12 [get_ports {gpio_a_out[13]}]
set_property SLEW SLOW [get_ports {gpio_a_out[13]}]
set_property PACKAGE_PIN L14 [get_ports {gpio_a_out[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_a_out[14]}]
set_property DRIVE 12 [get_ports {gpio_a_out[14]}]
set_property SLEW SLOW [get_ports {gpio_a_out[14]}]
set_property PACKAGE_PIN J17 [get_ports {gpio_a_out[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_a_out[15]}]
set_property DRIVE 12 [get_ports {gpio_a_out[15]}]
set_property SLEW SLOW [get_ports {gpio_a_out[15]}]

#GPIOB switch 0-15
set_property PACKAGE_PIN Y9 [get_ports {gpio_b_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_b_out[0]}]
set_property DRIVE 12 [get_ports {gpio_b_out[0]}]
set_property SLEW SLOW [get_ports {gpio_b_out[0]}]
set_property PACKAGE_PIN W9 [get_ports {gpio_b_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_b_out[1]}]
set_property DRIVE 12 [get_ports {gpio_b_out[1]}]
set_property SLEW SLOW [get_ports {gpio_b_out[1]}]
set_property PACKAGE_PIN Y7 [get_ports {gpio_b_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_b_out[2]}]
set_property DRIVE 12 [get_ports {gpio_b_out[2]}]
set_property SLEW SLOW [get_ports {gpio_b_out[2]}]
set_property PACKAGE_PIN Y8 [get_ports {gpio_b_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_b_out[3]}]
set_property DRIVE 12 [get_ports {gpio_b_out[3]}]
set_property SLEW SLOW [get_ports {gpio_b_out[3]}]
set_property PACKAGE_PIN AB8 [get_ports {gpio_b_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_b_out[4]}]
set_property DRIVE 12 [get_ports {gpio_b_out[4]}]
set_property SLEW SLOW [get_ports {gpio_b_out[4]}]
set_property PACKAGE_PIN AA8 [get_ports {gpio_b_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_b_out[5]}]
set_property DRIVE 12 [get_ports {gpio_b_out[5]}]
set_property SLEW SLOW [get_ports {gpio_b_out[5]}]
set_property PACKAGE_PIN V8 [get_ports {gpio_b_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_b_out[6]}]
set_property DRIVE 12 [get_ports {gpio_b_out[6]}]
set_property SLEW SLOW [get_ports {gpio_b_out[6]}]
set_property PACKAGE_PIN V9 [get_ports {gpio_b_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_b_out[7]}]
set_property DRIVE 12 [get_ports {gpio_b_out[7]}]
set_property SLEW SLOW [get_ports {gpio_b_out[7]}]
set_property PACKAGE_PIN AB6 [get_ports {gpio_b_out[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_b_out[8]}]
set_property DRIVE 12 [get_ports {gpio_b_out[8]}]
set_property SLEW SLOW [get_ports {gpio_b_out[8]}]
set_property PACKAGE_PIN AB7 [get_ports {gpio_b_out[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_b_out[9]}]
set_property DRIVE 12 [get_ports {gpio_b_out[9]}]
set_property SLEW SLOW [get_ports {gpio_b_out[9]}]
set_property PACKAGE_PIN V7 [get_ports {gpio_b_out[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_b_out[10]}]
set_property DRIVE 12 [get_ports {gpio_b_out[10]}]
set_property SLEW SLOW [get_ports {gpio_b_out[10]}]
set_property PACKAGE_PIN AA6 [get_ports {gpio_b_out[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_b_out[11]}]
set_property DRIVE 12 [get_ports {gpio_b_out[11]}]
set_property SLEW SLOW [get_ports {gpio_b_out[11]}]
set_property PACKAGE_PIN Y6 [get_ports {gpio_b_out[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_b_out[12]}]
set_property DRIVE 12 [get_ports {gpio_b_out[12]}]
set_property SLEW SLOW [get_ports {gpio_b_out[12]}]
set_property PACKAGE_PIN T6 [get_ports {gpio_b_out[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_b_out[13]}]
set_property DRIVE 12 [get_ports {gpio_b_out[13]}]
set_property SLEW SLOW [get_ports {gpio_b_out[13]}]
set_property PACKAGE_PIN R6 [get_ports {gpio_b_out[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_b_out[14]}]
set_property DRIVE 12 [get_ports {gpio_b_out[14]}]
set_property SLEW SLOW [get_ports {gpio_b_out[14]}]
set_property PACKAGE_PIN V5 [get_ports {gpio_b_out[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_b_out[15]}]
set_property DRIVE 12 [get_ports {gpio_b_out[15]}]
set_property SLEW SLOW [get_ports {gpio_b_out[15]}]

#GPIOC seg7 en, trigger
set_property PACKAGE_PIN A18 [get_ports {gpio_c_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_c_out[0]}]
set_property DRIVE 12 [get_ports {gpio_c_out[0]}]
set_property SLEW SLOW [get_ports {gpio_c_out[0]}]
set_property PACKAGE_PIN A20 [get_ports {gpio_c_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_c_out[1]}]
set_property DRIVE 12 [get_ports {gpio_c_out[1]}]
set_property SLEW SLOW [get_ports {gpio_c_out[1]}]
set_property PACKAGE_PIN B20 [get_ports {gpio_c_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_c_out[2]}]
set_property DRIVE 12 [get_ports {gpio_c_out[2]}]
set_property SLEW SLOW [get_ports {gpio_c_out[2]}]
set_property PACKAGE_PIN E18 [get_ports {gpio_c_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_c_out[3]}]
set_property DRIVE 12 [get_ports {gpio_c_out[3]}]
set_property SLEW SLOW [get_ports {gpio_c_out[3]}]
set_property PACKAGE_PIN F18 [get_ports {gpio_c_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_c_out[4]}]
set_property DRIVE 12 [get_ports {gpio_c_out[4]}]
set_property SLEW SLOW [get_ports {gpio_c_out[4]}]
set_property PACKAGE_PIN D19 [get_ports {gpio_c_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_c_out[5]}]
set_property DRIVE 12 [get_ports {gpio_c_out[5]}]
set_property SLEW SLOW [get_ports {gpio_c_out[5]}]
set_property PACKAGE_PIN E19 [get_ports {gpio_c_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_c_out[6]}]
set_property DRIVE 12 [get_ports {gpio_c_out[6]}]
set_property SLEW SLOW [get_ports {gpio_c_out[6]}]
set_property PACKAGE_PIN C19 [get_ports {gpio_c_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_c_out[7]}]
set_property DRIVE 12 [get_ports {gpio_c_out[7]}]
set_property SLEW SLOW [get_ports {gpio_c_out[7]}]
set_property PACKAGE_PIN F15 [get_ports {gpio_c_out[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_c_out[8]}]
set_property DRIVE 12 [get_ports {gpio_c_out[8]}]
set_property SLEW SLOW [get_ports {gpio_c_out[8]}]
set_property PACKAGE_PIN F13 [get_ports {gpio_c_out[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_c_out[9]}]
set_property DRIVE 12 [get_ports {gpio_c_out[9]}]
set_property SLEW SLOW [get_ports {gpio_c_out[9]}]
set_property PACKAGE_PIN F14 [get_ports {gpio_c_out[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_c_out[10]}]
set_property DRIVE 12 [get_ports {gpio_c_out[10]}]
set_property SLEW SLOW [get_ports {gpio_c_out[10]}]
set_property PACKAGE_PIN F16 [get_ports {gpio_c_out[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_c_out[11]}]
set_property DRIVE 12 [get_ports {gpio_c_out[11]}]
set_property SLEW SLOW [get_ports {gpio_c_out[11]}]
set_property PACKAGE_PIN E17 [get_ports {gpio_c_out[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_c_out[12]}]
set_property DRIVE 12 [get_ports {gpio_c_out[12]}]
set_property SLEW SLOW [get_ports {gpio_c_out[12]}]
set_property PACKAGE_PIN C14 [get_ports {gpio_c_out[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_c_out[13]}]
set_property DRIVE 12 [get_ports {gpio_c_out[13]}]
set_property SLEW SLOW [get_ports {gpio_c_out[13]}]
set_property PACKAGE_PIN C15 [get_ports {gpio_c_out[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_c_out[14]}]
set_property DRIVE 12 [get_ports {gpio_c_out[14]}]
set_property SLEW SLOW [get_ports {gpio_c_out[14]}]
set_property PACKAGE_PIN E13 [get_ports {gpio_c_out[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_c_out[15]}]
set_property DRIVE 12 [get_ports {gpio_c_out[15]}]
set_property SLEW SLOW [get_ports {gpio_c_out[15]}]

#GPIOD keyboard and button
set_property PACKAGE_PIN K4 [get_ports {gpio_d_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_d_out[0]}]
set_property DRIVE 12 [get_ports {gpio_d_out[0]}]
set_property SLEW SLOW [get_ports {gpio_d_out[0]}]
set_property PACKAGE_PIN J4 [get_ports {gpio_d_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_d_out[1]}]
set_property DRIVE 12 [get_ports {gpio_d_out[1]}]
set_property SLEW SLOW [get_ports {gpio_d_out[1]}]
set_property PACKAGE_PIN L3 [get_ports {gpio_d_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_d_out[2]}]
set_property DRIVE 12 [get_ports {gpio_d_out[2]}]
set_property SLEW SLOW [get_ports {gpio_d_out[2]}]
set_property PACKAGE_PIN K3 [get_ports {gpio_d_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_d_out[3]}]
set_property DRIVE 12 [get_ports {gpio_d_out[3]}]
set_property SLEW SLOW [get_ports {gpio_d_out[3]}]
set_property PACKAGE_PIN M2 [get_ports {gpio_d_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_d_out[4]}]
set_property DRIVE 12 [get_ports {gpio_d_out[4]}]
set_property SLEW SLOW [get_ports {gpio_d_out[4]}]
set_property PACKAGE_PIN K6 [get_ports {gpio_d_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_d_out[5]}]
set_property DRIVE 12 [get_ports {gpio_d_out[5]}]
set_property SLEW SLOW [get_ports {gpio_d_out[5]}]
set_property PACKAGE_PIN J6 [get_ports {gpio_d_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_d_out[6]}]
set_property DRIVE 12 [get_ports {gpio_d_out[6]}]
set_property SLEW SLOW [get_ports {gpio_d_out[6]}]
set_property PACKAGE_PIN L5 [get_ports {gpio_d_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_d_out[7]}]
set_property DRIVE 12 [get_ports {gpio_d_out[7]}]
set_property SLEW SLOW [get_ports {gpio_d_out[7]}]
set_property PACKAGE_PIN L4 [get_ports {gpio_d_out[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_d_out[8]}]
set_property DRIVE 12 [get_ports {gpio_d_out[8]}]
set_property SLEW SLOW [get_ports {gpio_d_out[8]}]
set_property PACKAGE_PIN R1 [get_ports {gpio_d_out[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_d_out[9]}]
set_property DRIVE 12 [get_ports {gpio_d_out[9]}]
set_property SLEW SLOW [get_ports {gpio_d_out[9]}]
set_property PACKAGE_PIN P1 [get_ports {gpio_d_out[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_d_out[10]}]
set_property DRIVE 12 [get_ports {gpio_d_out[10]}]
set_property SLEW SLOW [get_ports {gpio_d_out[10]}]
set_property PACKAGE_PIN P5 [get_ports {gpio_d_out[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_d_out[11]}]
set_property DRIVE 12 [get_ports {gpio_d_out[11]}]
set_property SLEW SLOW [get_ports {gpio_d_out[11]}]
set_property PACKAGE_PIN P4 [get_ports {gpio_d_out[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_d_out[12]}]
set_property DRIVE 12 [get_ports {gpio_d_out[12]}]
set_property SLEW SLOW [get_ports {gpio_d_out[12]}]
set_property PACKAGE_PIN P2 [get_ports {gpio_d_out[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_d_out[13]}]
set_property DRIVE 12 [get_ports {gpio_d_out[13]}]
set_property SLEW SLOW [get_ports {gpio_d_out[13]}]
# set_property PULLTYPE PULLUP [get_ports {gpio_d_out[14]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {gpio_d_out[14]}]
# set_property PULLTYPE PULLUP [get_ports {gpio_d_out[15]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {gpio_d_out[15]}]

# GPIOE EJTAG
set_property PACKAGE_PIN N2 [get_ports {gpio_e_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_e_out[0]}]
set_property DRIVE 12 [get_ports {gpio_e_out[0]}]
set_property SLEW SLOW [get_ports {gpio_e_out[0]}]
set_property PACKAGE_PIN M6 [get_ports {gpio_e_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_e_out[1]}]
set_property DRIVE 12 [get_ports {gpio_e_out[1]}]
set_property SLEW SLOW [get_ports {gpio_e_out[1]}]
set_property PACKAGE_PIN M5 [get_ports {gpio_e_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_e_out[2]}]
set_property DRIVE 12 [get_ports {gpio_e_out[2]}]
set_property SLEW SLOW [get_ports {gpio_e_out[2]}]
set_property PACKAGE_PIN P6 [get_ports {gpio_e_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_e_out[3]}]
set_property DRIVE 12 [get_ports {gpio_e_out[3]}]
set_property SLEW SLOW [get_ports {gpio_e_out[3]}]
set_property PACKAGE_PIN N5 [get_ports {gpio_e_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_e_out[4]}]
set_property DRIVE 12 [get_ports {gpio_e_out[4]}]
set_property SLEW SLOW [get_ports {gpio_e_out[4]}]
set_property PACKAGE_PIN J16 [get_ports {gpio_e_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_e_out[5]}]
set_property DRIVE 12 [get_ports {gpio_e_out[5]}]
set_property SLEW SLOW [get_ports {gpio_e_out[5]}]
set_property PACKAGE_PIN K18 [get_ports {gpio_e_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_e_out[6]}]
set_property DRIVE 12 [get_ports {gpio_e_out[6]}]
set_property SLEW SLOW [get_ports {gpio_e_out[6]}]
set_property PACKAGE_PIN K19 [get_ports {gpio_e_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_e_out[7]}]
set_property DRIVE 12 [get_ports {gpio_e_out[7]}]
set_property SLEW SLOW [get_ports {gpio_e_out[7]}]
# set_property PULLTYPE PULLUP [get_ports {gpio_e_out[8]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {gpio_e_out[8]}]
# set_property PULLTYPE PULLUP [get_ports {gpio_e_out[9]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {gpio_e_out[9]}]
# set_property PULLTYPE PULLUP [get_ports {gpio_e_out[10]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {gpio_e_out[10]}]
# set_property PULLTYPE PULLUP [get_ports {gpio_e_out[11]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {gpio_e_out[11]}]
# set_property PULLTYPE PULLUP [get_ports {gpio_e_out[12]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {gpio_e_out[12]}]
# set_property PULLTYPE PULLUP [get_ports {gpio_e_out[13]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {gpio_e_out[13]}]
# set_property PULLTYPE PULLUP [get_ports {gpio_e_out[14]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {gpio_e_out[14]}]
# set_property PULLTYPE PULLUP [get_ports {gpio_e_out[15]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {gpio_e_out[15]}]

# gpio_F_out empty
# set_property PULLTYPE PULLUP [get_ports {gpio_f_out[0]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {gpio_f_out[0]}]
# set_property PULLTYPE PULLUP [get_ports {gpio_f_out[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {gpio_f_out[1]}]
# set_property PULLTYPE PULLUP [get_ports {gpio_f_out[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {gpio_f_out[2]}]
# set_property PULLTYPE PULLUP [get_ports {gpio_f_out[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {gpio_f_out[3]}]
# set_property PULLTYPE PULLUP [get_ports {gpio_f_out[4]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {gpio_f_out[4]}]
# set_property PULLTYPE PULLUP [get_ports {gpio_f_out[5]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {gpio_f_out[5]}]
# set_property PULLTYPE PULLUP [get_ports {gpio_f_out[6]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {gpio_f_out[6]}]
# set_property PULLTYPE PULLUP [get_ports {gpio_f_out[7]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {gpio_f_out[7]}]
# set_property PULLTYPE PULLUP [get_ports {gpio_f_out[8]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {gpio_f_out[8]}]
# set_property PULLTYPE PULLUP [get_ports {gpio_f_out[9]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {gpio_f_out[9]}]
# set_property PULLTYPE PULLUP [get_ports {gpio_f_out[10]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {gpio_f_out[10]}]
# set_property PULLTYPE PULLUP [get_ports {gpio_f_out[11]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {gpio_f_out[11]}]
# set_property PULLTYPE PULLUP [get_ports {gpio_f_out[12]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {gpio_f_out[12]}]
# set_property PULLTYPE PULLUP [get_ports {gpio_f_out[13]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {gpio_f_out[13]}]
# set_property PULLTYPE PULLUP [get_ports {gpio_f_out[14]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {gpio_f_out[14]}]
# set_property PULLTYPE PULLUP [get_ports {gpio_f_out[15]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {gpio_f_out[15]}]
